api/produtos/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :produtos, only: [:index, :create]
    end
  end
end

api/produtos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

api/produtos/app/models/produto.rb
class Produto < ApplicationRecord
    validates :nome, presence: { message: "nome não pode ser vazio" }
    validates :preco, presence: { message: "preço não pode ser vazio" },
                    numericality: { greater_than_or_equal_to: 0, message: "preço deve ser um número positivo" }
    validates :descricao, presence: { message: "descrição não pode ser vazia" }

    validate :validar_tamanho_imagem

     private

    def validar_tamanho_imagem
        return if imagem.blank?

        tamanho_bytes = imagem.bytesize

        if tamanho_bytes > 2.megabytes
            errors.add(:imagem, "deve ter no máximo 2MB")
        end
    end
end

api/produtos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

api/produtos/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: "Produto was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy!

    respond_to do |format|
      format.html { redirect_to produtos_path, notice: "Produto was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.expect(produto: [ :nome, :preco, :imagem, :descricao ])
    end
end

api/produtos/app/helpers/application_helper.rb
module ApplicationHelper
end

api/produtos/app/helpers/posts_helper.rb
module PostsHelper
end

api/produtos/app/helpers/produtos_helper.rb
module ProdutosHelper
end

api/produtos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Produtos" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

api/produtos/app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :preco, style: "display: block" %>
    <%= form.text_field :preco %>
  </div>

  <div>
    <%= form.label :imagem, style: "display: block" %>
    <%= form.text_field :imagem %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.textarea :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

api/produtos/app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>">
  <p>
    <strong>Nome:</strong>
    <%= produto.nome %>
  </p>

  <p>
    <strong>Preco:</strong>
    <%= produto.preco %>
  </p>

  <p>
    <strong>Imagem:</strong>
    <%= produto.imagem %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= produto.descricao %>
  </p>

</div>

api/produtos/app/views/produtos/edit.html.erb
<% content_for :title, "Editing produto" %>

<h1>Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Show this produto", @produto %> |
  <%= link_to "Back to produtos", produtos_path %>
</div>

api/produtos/app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Produtos" %>

<h1>Produtos</h1>

<div id="produtos">
  <% @produtos.each do |produto| %>
    <%= render produto %>
    <p>
      <%= link_to "Show this produto", produto %>
    </p>
  <% end %>
</div>

<%= link_to "New produto", new_produto_path %>

api/produtos/app/views/produtos/new.html.erb
<% content_for :title, "New produto" %>

<h1>New produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Back to produtos", produtos_path %>
</div>

api/produtos/app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div>
  <%= link_to "Edit this produto", edit_produto_path(@produto) %> |
  <%= link_to "Back to produtos", produtos_path %>

  <%= button_to "Destroy this produto", @produto, method: :delete %>
</div>